name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  webhint:
    name: Webhint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Instalar dependencias
        run: npm ci
      - name: Webhint Report
        run: npx hint .

  stylelint:
    name: Stylelint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Instalar dependencias
        run: npm ci
      - name: Stylelint Report
        run: npx stylelint "**/*.{css,scss}"

  eslint:
    name: ESLint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Instalar dependencias
        run: npm ci
      - name: ESLint Report
        run: npx eslint .

  nodechecker:
    name: node_modules checker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check node_modules existence
        run: |
          if [ -d "node_modules/" ]; then 
            echo -e "\e[1;31mEl directorio node_modules fue empujado al repositorio. Elimínalo y agrégalo a .gitignore." 
            exit 1
          fi
